channels:
  - "macbookvisuals"
  - "yung.iam"
  - "rivan21332"
  - "heygaree"
  - "mr.ego42"
  - "0ne966"
  - ".kingarienda"
  - "notricwrz"
  - "spotifylyrics446"
  - "nelsonamaraal"
  - "mkmusic216"
  - "teehayyz"
  - "weluvskb23"
  - "sirrr.r"


db_path : database/tiktok-sound.json

spotify_client_id: "enter-here"
spotify_client_secret: "enter-here"

genres : 
  hip_hop: ["hip_hop","rap","trap","hip hop"]
  alternative: ["alternative","alt"]
  rock_music: ["rock_music","rock","metal","punk"]
  pop: ["pop","electropop"]
  electronic_dance_music: ["edm","electronic_dance_music","electronic","house","techno","dance"]
  latin_music: ["latin","reggaeton","latina","urbano"]
  k_pop: ["k-pop","kpop"]
  rnb: ["r&b","soul","rnb"]

  general: []
